import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/pageComponents/layout/header";
import { Toaster } from 'sonner';

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" >
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-green-50 antialiased  text-black`}
			>
				<Header />
				<main className=" mx-auto lg:max-w-[80%] px-4 mt-24">
					{children}
					<Toaster />
				</main>
			</body>
		</html>
	);
}
